from typing import TypedDict

class EstimatedCost(TypedDict):
    usd: str
    input_usd: str
    cached_input_usd: str
    cache_write_input_usd: str
    output_usd: str
    service_tier: str

class Usage(TypedDict):
    input_tokens: int
    cached_input_tokens: int
    cache_write_input_tokens: int
    output_tokens: int
    reasoning_output_tokens: int
    total_tokens: int
    estimated_cost: EstimatedCost | None
    cost_status: str

class SessionSnapshot:
    @staticmethod
    def from_json(encoded: str) -> SessionSnapshot: ...
    def to_json(self) -> str: ...
    @property
    def version(self) -> int: ...
    @property
    def workspace(self) -> str: ...

class TurnResult:
    @property
    def final_message(self) -> str: ...
    def usage(self) -> Usage: ...
    def snapshot(self) -> SessionSnapshot: ...

class Turn:
    def steer(self, instruction: str) -> None: ...
    def cancel(self) -> None: ...
    def result(self) -> TurnResult: ...

class AgentEvent:
    @property
    def protocol_version(self) -> int: ...
    @property
    def request_id(self) -> str: ...
    @property
    def seq(self) -> int: ...
    @property
    def kind(self) -> str: ...
    @property
    def payload(self) -> dict[str, object]: ...
    @property
    def payload_json(self) -> str: ...

class AgentEvents:
    @property
    def request_id(self) -> str: ...
    def recv(self) -> AgentEvent | None: ...
    def recv_json(self) -> str | None: ...

class Nanocodex:
    def __new__(
        cls,
        api_key: str | None = ...,
        *,
        auth_file: str | None = ...,
        thinking: str = ...,
        reasoning_mode: str = ...,
        fast_mode: bool = ...,
        workspace: str | None = ...,
        instructions: str | None = ...,
        session_id: str | None = ...,
        prompt_cache_key: str | None = ...,
        resume: SessionSnapshot | None = ...,
        websocket_url: str | None = ...,
        api_base_url: str | None = ...,
    ) -> tuple[Nanocodex, AgentEvents]: ...
    @property
    def session_id(self) -> str: ...
    def prompt(self, prompt: str) -> Turn: ...
    def set_thinking(self, thinking: str) -> None: ...
    def set_fast_mode(self, enabled: bool) -> None: ...
    def compact(self) -> None: ...
    def spawn(self) -> tuple[Nanocodex, AgentEvents]: ...
    def fork(self) -> tuple[Nanocodex, AgentEvents]: ...
    def fork_from(self, result: TurnResult) -> tuple[Nanocodex, AgentEvents]: ...
    def shutdown(self) -> None: ...

__version__: str
